name: Backend Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    # Build JAR File
    - name: Build JAR File
      run: ./mvnw clean package -DskipTests

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and Tag Docker Image
    - name: Build Docker Image
      run: |
        IMAGE_NAME=imtiyazhirani/jobportal-backend
        IMAGE_TAG=${{ github.sha }}
        docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .

    # Push Docker Image to Docker Hub
    - name: Push Docker Image
      run: |
        IMAGE_NAME=imtiyazhirani/jobportal-backend
        IMAGE_TAG=${{ github.sha }}
        docker push $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:latest
